spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/ziemniakidb'
    password: 'root'
    username: 'root'
  jpa:
    hibernate:
      ddl-auto: update
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/demo-app-relm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: master
  client-id: admin-cli
  username: admin
  password: admin